version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ../..
      dockerfile: ./ops-tools/images/app/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/school
    ports:
      - "8888:8888"
    networks:
      docker-practice-net:
        ipv4_address: 171.8.8.10
        aliases:
          - app
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:11.13-alpine
    environment:
      POSTGRES_DB: school
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: school
      PG_DATA: ./var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db_dump
    networks:
      docker-practice-net:
        ipv4_address: 171.8.8.11
        aliases:
          - postgres
  redis:
    container_name: redis
    image: redis
    environment:
      REDIS_PORT: 6379
    ports:
      - "6379:6379"
    networks:
      docker-practice-net:
        ipv4_address: 171.8.8.12
        aliases:
          - redis

networks:
  docker-practice-net:
    name: docker-practice-net
    ipam:
      config:
        - subnet: "171.8.8.0/24"